#!/usr/bin/env bash

# echo $PATH
# which flake8
# which black

if [ "$1" != "" ]; then
    WHERE="$1"
    shift
else
    WHERE="."
fi

echo Black...
black "$WHERE" $* 
echo Flake8...
flake8 "$WHERE" $* # || exit 1
echo Mypy...
mypy "$WHERE" $* || exit 1
