#!/bin/bash

# TODO detect args that look like options and pass to git;
# don't require -- for disambiguation

OTHER="$1"

if [ -z "$OTHER" ]; then
    OTHER=origin/master
elif [ "$OTHER" = "--" ]; then
    OTHER=origin/master
    shift
else
    shift
fi


echo Comparing to branch "$OTHER"...
git log $@ "$OTHER"...

# More verbose way to do it:
#BRANCH=`git branch | grep '*' | cut -d ' ' -f 2`
#git log $@ "$BRANCH" ^"$OTHER"

