#!/bin/bash

warn() { echo "$*" >&1; }
shout() { echo "$0: $*" >&2; }  # Just echo an error and the program name
barf() { shout "$*"; exit 111; }
safe() { "$@" || barf "cannot $*"; }

SCRIPT_NAME="`basename $0`"

function usage {
    warn "Usage: git make-branch [start_point] branch-name [tag_name]"
    warn
    warn "[start_point] is NOT tracked."
    warn "This is to avoid accidental pushes to the wrong remote branch."
    warn "Typically, 'git push origin branch-name' is all you need."
    warn
    warn "If [start_point] is not given, origin/master is used."
    warn "If [tag_name] is not given, <branch-name>_start_point_<date>"
    warn "is used." 
}


for arg in "$@"; do
    if [ "$arg" == "-h" -o "$arg" == "--help" ]; then
        usage
        exit 0
    fi
done

if [ $# -eq 0 ]; then
    shout "Not enough arguments."
    usage
    exit 1
fi

START_POINT="origin/master"

if [ "$#" -gt 1 ]; then
	START_POINT="$1"
    shift
fi

safe git log -1 "$START_POINT" > /dev/null

BRANCH_NAME="$1"
shift

if [ -z "$BRANCH_NAME" ]; then
	usage
	exit 1
fi

DATE=`date +"%Y%m%d"`
TAG_NAME="${BRANCH_NAME}_start_point_${DATE}"

if [ "$#" -gt 0 ]; then
	TAG_NAME="$1"
	shift
fi

if [ "$#" -gt 0 ]; then
	shout Too many arguments.
	usage
	exit 1
fi

safe git tag "$TAG_NAME" "$START_POINT"
echo "Tagged $TAG_NAME starting from $START_POINT"
safe git checkout --no-track "$TAG_NAME" -b "$BRANCH_NAME"
