#!/bin/sh

for branchname in `git branch $@ | sed s/^..// | grep -v -- '->'`; do
    echo `git log --color=always -1 --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" ${branchname} --`\\t"${branchname}";
done | sort
